updating ci/cd3

diff --git a/.github/workflows/azure-kubernetes-service.yml b/.github/workflows/azure-kubernetes-service.yml
--- a/.github/workflows/azure-kubernetes-service.yml
+++ b/.github/workflows/azure-kubernetes-service.yml
@@ -32,14 +32,23 @@ jobs:
       # Install Node.js dependencies
       - name: Install dependencies
         run: npm ci  # Use 'npm ci' instead of 'npm install' for CI/CD
-        
+      
+      - name: Check Azure CLI Installation
+        run: |
+          echo "Checking Azure CLI installation..."
+          which az || echo "Az CLI not found in PATH"
+          az version || echo "Failed to get Az CLI version"
+          az account show || echo "No active account found"
+      
       # Logs in with your Azure credentials
       - name: Azure login
         uses: azure/login@v1.4.6
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      
+        env:
+          ACTIONS_STEP_DEBUG: true
 
       # Builds and pushes an image up to your Azure Container Registry
       - name: Build and push image to ACR
